---
title: Gnibl Box
timezone: Australia/Sydney
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
Footer Menu Links:
- Title: 
  URL: 
social_footer:
- site: Facebook
  url: https://facebook.com/gnibl
  image: "/uploads/Facebook.svg"
- site: Instagram
  url: https://instagram.com/gnibl
  image: "/uploads/Instagram.svg"
Accepted Payments:
- Name: 
  Image: 
