---
title: Gnibl Box
timezone: Australia/Sydney
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
Contact email: info@gnibl.com.au
Meta Description: 
OG Image: 
Footer Menu Links:
- Title: About
  URL: "/#about"
- Title: FAQs
  URL: "/#faqs"
- Title: Pricing
  URL: "/pricing"
- Title: Enter To Win!
  URL: gniblbox.com.au/officeworkoutchallenge/
Footer Social Links:
- website: Facebook
  url: https://facebook.com/gnibl
  image: "/uploads/Facebook.svg"
- website: Instagram
  url: https://instagram.com/gnibl_snacks
  image: "/uploads/Instagram.svg"
- website: Twitter
  url: https://twitter.com/gniblsnacks
  image: "/uploads/Twitter.svg"
Accepted Payments:
- name: Visa
  image: "/uploads/Visa.svg"
- name: MasterCard
  image: "/uploads/Mastercard.svg"
- name: American Express
  image: "/uploads/amex.svg"
- name: Discover
  image: "/uploads/discover.svg"
Terms & Conditions file: "/uploads/Gnibl%20Box%20Terms%20and%20Conditions%201.0.pdf"
